### ISSUE TITLE
Elasticsearch: [class_cast_exception] java.lang.String cannot be cast to java.util.Map

### ISSUE THREAD

**Issue by Skib4** [pelias/docker#163] opened 2020-01-10 16:23 UTC
Hi everyone! 
I've got problem with Pelias build. I've followed guide "Quickstart build script" but I've got problem on "pelias elastic create" step.

**Here's output:**
```
root@srv ~/pelias/projects/poland # pelias compose pull
Pulling libpostal     ... done
Pulling schema        ... done
Pulling api           ... done
Pulling placeholder   ... done
Pulling whosonfirst   ... done
Pulling openstreetmap ... done
Pulling openaddresses ... done
Pulling transit       ... done
Pulling csv-importer  ... done
Pulling polylines     ... done
Pulling interpolation ... done
Pulling pip           ... done
Pulling elasticsearch ... done
Pulling fuzzy-tester  ... done
root@srv ~/pelias/projects/poland # pelias elastic start 
Creating pelias_elasticsearch ... done
root@srv ~/pelias/projects/poland # pelias elastic wait
waiting for elasticsearch service to come up
.......Elasticsearch up!
root@srv ~/pelias/projects/poland # pelias elastic create

--------------
 create index 
--------------

[class_cast_exception] java.lang.String cannot be cast to java.util.Map 

root@srv ~/pelias/projects/poland # 

```
---

**And here's my pelias.json file** 
```
{
  "logger": {
    "level": "info",
    "timestamp": false
  },
  "esclient": {
    "apiVersion": "5.6",
    "hosts": [
      { "host": "elasticsearch" }
    ]
  },
  "elasticsearch": {
    "settings": {
      "index": {
        "refresh_interval": "10s",
        "number_of_replicas": "0",
        "number_of_shards": "12"
      }
    }
  },
  "api": {
    "textAnalyzer": "libpostal",
    "services": {
      "placeholder": { "url": "http://placeholder:4100" },
      "pip": { "url": "http://pip:4200" },
      "interpolation": { "url": "http://interpolation:4300" },
      "libpostal": { "url": "http://libpostal:4400" }
    }
  },
  "imports": {
    "adminLookup": {
      "enabled": true
    },
    "geonames": {
      "datapath": "/disk2/data/geonames",
      "countryCode": "PL"
    },
    "openstreetmap": {
      "download": [
        { "sourceURL": "http://download.geofabrik.de/europe/poland-latest.osm.pbf" }
      ],
      "leveldbpath": "/tmp",
      "datapath": "/disk2/data/openstreetmap",
      "import": [{
        "filename": "poland-latest.osm.pbf"
      }]
    },
    "whosonfirst": {
      "datapath": "/disk2/data/whosonfirst",
      "importVenues": false,
      "importPostalcodes": false
    }
  }
} 
```

Java version is 1.8.0_201
Has anyone similar problem?

**Comment by missinglink** [comment] 2020-01-10 16:59
We actually dropped support for ES5 this week (as ES7 support is coming shortly)
Please try again using the latest version of ES6

closing as a dupe of https://github.com/pelias/schema/issues/428
fixed in https://github.com/pelias/schema/pull/429

**Closed by missinglink** 2020-01-10 16:59 UTC

**Comment by missinglink** [comment] 2020-01-10 17:25
Please do a `pelias compose pull` and try again, it should still fail but with a descriptive error message :)
