### ISSUE TITLE
Errors and failed tests following generic build workflow with portland-metro example

### ISSUE THREAD

**Issue by chriszrc** [pelias/docker#60] opened 2018-12-23 15:34 UTC
First, I'll start by saying that in spite of the failed tests and copious errors, it appears that pelias is at least working (as in the example queries return results). However, I'm not sure of what to make of these errors:

There were lots of these:
```
error: [dbclient] invalid resp from es bulk index operation
info: [dbclient] retrying batch [500]
error: [dbclient] esclient error message=Request Timeout after 120000ms, status=408, displayName=RequestTimeout, stack=Error: Request Timeout after 120000ms
    at /code/pelias/openstreetmap/node_modules/elasticsearch/src/lib/transport.js:355:15
    at Timeout.<anonymous> (/code/pelias/openstreetmap/node_modules/elasticsearch/src/lib/transport.js:384:7)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

There were thousands of these:
```
error: [dbclient] [429] type=es_rejected_execution_exception, reason=rejected execution of org.elasticsearch.transport.TransportService$7@50b7cdab on EsThreadPoolExecutor[bulk, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@e1895bd[Running, pool size = 4, active threads = 4, queued tasks = 200, completed tasks = 2679]]
```

This came up only once:
```
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-borough-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-localadmin-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-macrocounty-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-macroregion-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-dependency-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-empire-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-marinearea-latest.csv
warn: [wof-pip-service:master] unable to locate /data/whosonfirst/meta/whosonfirst-data-ocean-latest.csv
```

Running the tests, the results were:
Aggregate test results
Pass: 355
Improvements: 0
Fail: 41
Placeholders: 0
Regressions: 80
Took 12633ms
Test success rate 83.19%

Is all of this normal? Do I actually have a working geocoder for portland at least?

**Comment by orangejulius** [comment] 2019-01-29 22:37
Hey @chriszrc,
Sorry, we missed this one somehow.

The warnings in your second code snippet are normal, but the Elasticsearch rejected execution errors are the standard error when Elasticsearch is a bit overloaded. It does mean that some records weren't inserted into Elasticsearch, so you don't quite have a complete build, although as you can see with your 83% test success rate, you're mostly there (it should be close to but not quite 100% most of the time).

How much CPU power and RAM does the machine you were running this on have? 2-4 CPUs and 8GB RAM is a good minimum. You can also tweak some settings to make things work on an even smaller machine, but the defaults should work well given that level of hardware.

**Comment by chriszrc** [comment] 2019-01-30 13:21
Hi,
Thanks for getting back to me, that's great to hear that some of these are expected, and for the other errors, it might be a machine issue. This was running in docker, which I think had access to the resources specified in the readme (4 processors, 8gb ram) as specified in the docker preferences. I'll try increasing it some more and see if that fixes it, thanks!

**Comment by missinglink** [comment] 2019-01-30 20:54
The `es_rejected_execution_exception` is caused when the data importer is sending data to elasticsearch faster than it can accept it.
This is most often caused when the elasticsearch process is starved of CPU.

I don't suppose you're running docker on a mac? if so, then docker might not have access to all the resources of your system.
There is some info in the `Prerequisites` section of the readme which explains how to configure that.

**Comment by chriszrc** [comment] 2019-01-30 22:12
You are indeed correct, docker on a macbook pro. I did see this section:

https://github.com/pelias/docker#prerequisites

And I did install coreutils, but I didn't completely max out the docker resources, I'll give that a try-

**Comment by jeremy-rutman** [comment] 2019-03-29 12:23
For a plain-vanilla install of portland-metro exactly according to install instructions (no proxies or other changes) , using docker 18.09.4, and docker-compose version 1.23.2 on a fresh ubuntu 18.04.2 LTS  on an AWS m5a.4xlarge instance (16 cpu 64 GiB ram, 700Gssd) I get the following: 

```
Aggregate test results                                      
Pass: 196                                             
Improvements: 0                                           
Fail: 41                                                                                       
Placeholders: 0                                                                                    
Regressions: 239                                                                             
Took 7205ms                                                                                      
Test success rate 49.79%                            
                                                        
FATAL ERROR: 239 regression(s) detected.                             

```


There were a bunch like this ( I guess these are the 'fails') : 
```
 ✘ [65] "{"text":"14587 SW DAUER CT, Portland, OR"}": score 3 out of 4
  diff:                               
    name                         
      expected: 14587 SW DAUER CT         
      actual:   PORTLAND                
```

and regressions like this : 
```
** ✘ regression [40] "{"text":"17175 SW TVH aloha Oregon"}": score 3 out of 4
  diff:                                    
    name                                
      expected: 17175 SW TUALATIN VALLEY HIGHWAY
      actual:   ALOHA                   
```
and like this 
```
**  ✘ regression [466] "{"text":"309 SE 129TH AVE, Portland, Oregon"}": Unexpected status code 500
```

As an aside it looks like the 16 cpus are way overkill at least for import , unless I have missed some config file. The load average looks south of 4%.

**Comment by jeremy-rutman** [comment] 2019-04-06 22:41
I'm also seeing a bunch of  es_rejected_execution_exeption errors during `pelias prepare all` :

```
error: [dbclient-openaddresses] [429] type=es_rejected_execution_exception, reason=rejected execution of org.elasticsearch.transport.TransportService$4@780a9e2c on EsThreadPoolExecutor[bulk, queue capacity = 50, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@5556905f[Running, pool size = 16, active threads = 16, queued tasks = 50, completed tasks = 2456798]]                                                                                     
error: [dbclient-openaddresses] [429] type=es_rejected_execution_exception, reason=rejected execution of org.elasticsearch.transport.TransportService$4@737e3062 on EsThreadPoolExecutor[bulk, queue capacity = 50, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@5556905f[Running, pool size = 16, active threads = 16, queued tasks = 50, completed tasks = 2456798]]                                                                                     
error: [dbclient-openaddresses] [429] type=es_rejected_execution_exception, reason=rejected execution of org.elasticsearch.transport.TransportService$4@780a9e2c on EsThreadPoolExecutor[bulk, queue capacity = 50, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@5556905f[Running, pool size = 16, active threads = 16, queued tasks = 50, completed tasks = 2456798]]                                                                                     
info: [dbclient-openaddresses] retrying batch [429]                                                                                                                                                 
info: [dbclient-openaddresses] retrying batch [429]                                                                                                                                                 
error: [dbclient-openaddresses] transaction error invalid bulk payload length. Payload received: []                                                                                                 
info: [dbclient-openaddresses] retrying batch [429]                                                                                                                                                 
info: [dbclient-openaddresses] retrying batch [429]                                                                                                                                                 
info: [dbclient-openaddresses] retrying batch [429]                                                                                                                                                 
info: [dbclient-openaddresses] retrying batch [429]                                                                                                                                                 
error: [dbclient-openaddresses] transaction error reached max retries                                                                                                                               
info: [dbclient-openaddresses]  paused=false, transient=1, current_length=1, indexed=97841000, batch_ok=195682, batch_retries=0, failed_records=0, address=97841000, persec=5350, batch_error=35   
```

**Comment by jeremy-rutman** [comment] 2019-04-09 17:07
`curl -XPUT localhost:9200/_cluster/settings -d '{ "transient" : { "threadpool.bulk.queue_size" : 500 } }` at the cli will let you change the  queue size, this helped my installs when using a single node , avoiding the rejected_execution_exception

**Comment by chriszrc** [comment] 2019-04-17 00:57
@orangejulius Ok, I maxed out all the resouces on my macbook, and just as you predicted, the build now completes without any of the elasticsearch exceptions. This is now what I'm seeing for the test run:

Aggregate test results
Pass: 390
Improvements: 2
Fail: 39
Placeholders: 0
Regressions: 45
Took 18248ms
Test success rate 90.51%

Is that what's expected?

**Comment by orangejulius** [comment] 2019-05-12 14:32
90% success rate looks about right. I also just opened https://github.com/pelias/dbclient/pull/108 which might help setups with less CPU available to have a higher chance of success.

Since I think we've probably figured out what the problem was, I'm going to close this.

**Closed by orangejulius** 2019-05-12 14:32 UTC
