### ISSUE TITLE
Having WOF download custom data

### ISSUE THREAD

**Issue by Devmaticz** [pelias/docker#65] opened 2019-01-22 22:01 UTC
Hello,

I am trying to creat a project that download only WOF data from my own URL, to make pelias geocode only my specefic geometries.

Any one succeeded on that, or even tried to ?

Thank you

**Comment by orangejulius** [comment] 2019-01-25 17:42
Another dupe of https://github.com/pelias/whosonfirst/issues/418 :)

**Closed by orangejulius** 2019-01-25 17:42 UTC
