### ISSUE TITLE
[north-america] placeholder: INSERT INTO docs (id, json) VALUES ($id, $json)

### ISSUE THREAD

**Issue by divE4pip** [pelias/docker#200] opened 2020-06-07 20:52 UTC
**Describe the bug**
When I run `pelias prepare placeholder` I get this error in the logs. Is this a critical error or it can be safely ignored?

**Steps to Reproduce**
```
cd pelias/projects/north-america
pelias compose pull
pelias elastic start
pelias elastic wait
pelias elastic create
pelias download all
pelias prepare placeholder
```

**Expected behavior**
No errors in logs

**Environment (please complete the following information):**
 - OS: Linux

docker --version
Docker version 19.03.8, build afacb8b7f0

docker-compose --version
docker-compose version 1.25.0, build unknown

**Logs**
```
pelias prepare placeholder
Creating extract at /data/placeholder/wof.extract
import...
SqliteError: malformed JSON
    at Statement.run (<anonymous>)
    at DocStore.set (/code/pelias/placeholder/lib/DocStore.js:67:10)
    at Placeholder.insertWofRecord (/code/pelias/placeholder/prototype/wof.js:210:14)
    at DestroyableTransform.insert [as _transform] (/code/pelias/placeholder/cmd/load.js:15:19)
    at DestroyableTransform.Transform._read (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_readable.js:619:20)
INSERT INTO docs (id, json) VALUES ($id, $json)
SqliteError: malformed JSON
    at Statement.run (<anonymous>)
    at DocStore.set (/code/pelias/placeholder/lib/DocStore.js:67:10)
    at Placeholder.insertWofRecord (/code/pelias/placeholder/prototype/wof.js:210:14)
    at DestroyableTransform.insert [as _transform] (/code/pelias/placeholder/cmd/load.js:15:19)
    at DestroyableTransform.Transform._read (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/code/pelias/placeholder/node_modules/readable-stream/lib/_stream_readable.js:619:20)
populate fts...
optimize...
close...
Done!
```

**Comment by missinglink** [comment] 2020-06-08 11:26
Possible duplicate of https://github.com/pelias/placeholder/issues/183

**Comment by orangejulius** [comment] 2020-09-15 16:12
I believe this was an issue in WOF data that was fixed upstream as described in https://github.com/pelias/placeholder/issues/183

**Closed by orangejulius** 2020-09-15 16:12 UTC
Labels: bug
